---
# file: tasks/main.yml

- name: Install yum-cron
  yum:
    name: yum-cron
    state: latest
  tags:
    - yumcron

- name: Copy configuration files
  template:
    src: "yum-cron.conf.j2"
    dest: "/etc/yum/yum-cron.conf"
  tags:
    - yumcron
    - yumcron_config

- name: Start and enable yum-cron
  service:
    name: yum-cron
    state: started
    enabled: yes
  tags:
    - yumcron
