Vagrant.configure(2) do |config|

  config.vm.define "yum-cron-centos" do |centos|
    centos.vm.box = "centos"
    centos.vm.hostname = "yum-cron-centos"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "yum-cron-centos"
      vbox.cpus = 1
      vbox.memory = 512
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.compatibility_mode = "2.0"
  end

end
